name: Build and push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for changes to this file on the main branch
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout remote
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: zalando/spilo
          ref: 4.1-p2

      - name: Registry login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive spilo image name
        id: image
        working-directory: postgres-appliance
        run: |
          VERSION=$(git describe --tags --always --dirty)
          PGVERSION=$(sed -n 's/^ARG PGVERSION=\([1-9][0-9]*\).*$/\1/p' Dockerfile)
          IMAGE="ghcr.io/bendikwa/spilo-$PGVERSION:$VERSION"
          echo "NAME=$IMAGE" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        
      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: "postgres-appliance/"
          push: true
          tags: ${{ steps.image.outputs.NAME }}
